# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs'

plugin 'cocoapods-art', :sources => [
  'cleardil-cocoapods-local'
]

target 'iOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'cleardil_ios_sdk', '1.2.2'

  target 'iOSExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSExampleUITests' do
    # Pods for testing
  end

end
