# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSExample
#plugin 'cocoapods-art', :sources => [
 # 'trunk',
  #'cleardil-cocoapods'
#]

pod 'cleardil_kyc_pod', :git => 'https://github.com/AbdelSefiane/cleardil_kyc_pod.git', :tag => '1.0.8'

  target 'iOSExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSExampleUITests' do
    # Pods for testing
  end

end
