# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
pod 'cleardil_ios_sdk', :git => 'https://github.com/ClearDil/cleardil_ios_sdk.git', :tag => '1.1.0'

  target 'iOSExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSExampleUITests' do
    # Pods for testing
  end

end
